In [1]:
import numpy as np

* slicing

In [145]:
x=np.arange(20)
print(x)
print(x[1:3])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 2]


In [7]:
x=np.arange(20).reshape(4,5)
print(x)
print(x[1:3])
print(x[1:3, 1:3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 6  7]
 [11 12]]


In [13]:
x=np.arange(30).reshape(2,5,3)
print(x)
print(x[:,3:5, 1])


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
[[10 13]
 [25 28]]


* indexing & boolean indexing

In [15]:
 a = np.arange(20).reshape(4,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [17]:
a[1][1]

6

In [20]:
a[1,1]

6

In [21]:
a[[1,1],[1,2]]

array([6, 7])

In [22]:
print(a > 3)

[[False False False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [23]:
a[a>3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
a[a==1] 

array([1])

In [25]:
a[~(a==1)]

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [28]:
print(a[(a > 3) |(a < 9)])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


* random

In [33]:
np.random.rand(5,5)

array([[0.550066  , 0.14834197, 0.64153345, 0.54005875, 0.25017742],
       [0.91223956, 0.12241193, 0.21989047, 0.4267682 , 0.80078448],
       [0.03223383, 0.58033571, 0.89898102, 0.53876375, 0.75269586],
       [0.44289431, 0.7752361 , 0.82740671, 0.54345205, 0.76460416],
       [0.68005991, 0.52420172, 0.24055747, 0.05626212, 0.42178579]])

In [34]:
np.random.randint(1,10)

8

In [35]:
np.random.randint(1, 10, size=(5))

array([3, 1, 3, 8, 2])

In [36]:
np.random.choice(100, size=(3,4))

array([[93,  6, 84, 77],
       [46, 48,  0, 40],
       [82, 84, 38, 75]])

In [37]:
x= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
np.random.choice(x, size=(2,2))

array([[7, 9],
       [3, 9]])

In [38]:
import random
random.choice([1, 2, 3, 4, 5, 6, 7, 8, 9])

6

* 특별한 형태의 행렬

In [41]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
x = np.random.randint(1,10,size=(5,5))
x

array([[8, 5, 5, 6, 6],
       [3, 1, 9, 3, 6],
       [2, 9, 4, 4, 9],
       [2, 2, 2, 2, 5],
       [2, 6, 6, 3, 3]])

In [47]:
x.ravel()

array([8, 5, 5, 6, 6, 3, 1, 9, 3, 6, 2, 9, 4, 4, 9, 2, 2, 2, 2, 5, 2, 6,
       6, 3, 3])

In [48]:
x.ravel(order='F')

array([8, 3, 2, 2, 2, 5, 1, 9, 2, 6, 5, 9, 4, 2, 6, 6, 3, 4, 2, 3, 6, 6,
       9, 5, 3])

In [49]:
x.flatten()

array([8, 5, 5, 6, 6, 3, 1, 9, 3, 6, 2, 9, 4, 4, 9, 2, 2, 2, 2, 5, 2, 6,
       6, 3, 3])

In [50]:
x.flatten(order='F')

array([8, 3, 2, 2, 2, 5, 1, 9, 2, 6, 5, 9, 4, 2, 6, 6, 3, 4, 2, 3, 6, 6,
       9, 5, 3])

In [51]:
temp = x.ravel()
print(temp)

[8 5 5 6 6 3 1 9 3 6 2 9 4 4 9 2 2 2 2 5 2 6 6 3 3]


In [52]:
temp[0] = 100
print("x:\n", x)
print("\ntemp: \n", temp)

x:
 [[100   5   5   6   6]
 [  3   1   9   3   6]
 [  2   9   4   4   9]
 [  2   2   2   2   5]
 [  2   6   6   3   3]]

temp: 
 [100   5   5   6   6   3   1   9   3   6   2   9   4   4   9   2   2   2
   2   5   2   6   6   3   3]


In [53]:
x[0] = 6
x

array([[6, 6, 6, 6, 6],
       [3, 1, 9, 3, 6],
       [2, 9, 4, 4, 9],
       [2, 2, 2, 2, 5],
       [2, 6, 6, 3, 3]])

In [54]:
temp = x.flatten()
temp[0] = 100
print("x:\n", x)
print("\ntemp: \n", temp)

x:
 [[6 6 6 6 6]
 [3 1 9 3 6]
 [2 9 4 4 9]
 [2 2 2 2 5]
 [2 6 6 3 3]]

temp: 
 [100   6   6   6   6   3   1   9   3   6   2   9   4   4   9   2   2   2
   2   5   2   6   6   3   3]


* concatenate

In [56]:
x = np.arange(1,4)
y = np.arange(4,7)
print(x)
print(y)

[1 2 3]
[4 5 6]


In [63]:
x = np.arange(10).reshape(2, 5)
y = np.arange(10,20).reshape(2, 5)
print(x)
print(y)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]


In [64]:
np.concatenate([x,y], axis=1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

* split

In [65]:
x = np.arange(12)
print(x)
np.split(x,4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [67]:
x = np.arange(16).reshape(4,4)
print(x)
np.split(x,2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [69]:
x=np.arange(16).reshape(4,4)
print(x)
np.split(x, 2, axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

* broadcast

In [80]:
x = np.array([1, 2, 3])
print(x)
x+1

[1 2 3]


array([2, 3, 4])

In [86]:
x = np.arange(1,10).reshape(3,3)
y = np.arange(1,4)
print(x.shape)
print(y.shape)
print(x)
print(y)

(3, 3)
(3,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]


In [88]:
x+y

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [93]:
a = np.array([10, 20, 30]).reshape(3,1)
b = np.arange(1,4)
print(a.shape)
print(b.shape)

(3, 1)
(3,)


In [94]:
a+b

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [77]:
a = np.arange(12).reshape(4,-1)
b = np.arange(100,103)
c = np.arange(1000, 1004)
d = b.reshape(1, 3)

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

print(a)
print(b)
print(c)
print(d)

(4, 3)
(3,)
(4,)
(1, 3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[100 101 102]
[1000 1001 1002 1003]
[[100 101 102]]


In [78]:
a+b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [95]:
a+c

array([[1010, 1011, 1012, 1013],
       [1020, 1021, 1022, 1023],
       [1030, 1031, 1032, 1033]])

In [96]:
a+d

array([[110, 111, 112],
       [120, 121, 122],
       [130, 131, 132]])

* 실습 1

In [102]:
x=[1, 2, 3, 4, 5, 6, 7, 8, 9]
y=[10, 20, 30, 40, 50, 60, 70, 80, 90]

a = np.array(x).reshape(3,3)
b = np.array(y).reshape(3,3)

In [105]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [103]:
a+b

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [106]:
a.dot(b)

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

* 실습

In [111]:
a = np.linspace(1, 20, 30)
print(a+10)

[11.         11.65517241 12.31034483 12.96551724 13.62068966 14.27586207
 14.93103448 15.5862069  16.24137931 16.89655172 17.55172414 18.20689655
 18.86206897 19.51724138 20.17241379 20.82758621 21.48275862 22.13793103
 22.79310345 23.44827586 24.10344828 24.75862069 25.4137931  26.06896552
 26.72413793 27.37931034 28.03448276 28.68965517 29.34482759 30.        ]


In [165]:
x=np.random.randint(1, 101, size=(200)).reshape(2,10,10)
print(x)

[[[ 13  64  92  92  21  29  61  76 100  91]
  [  2  84  46  66   9  97  68  73   5  69]
  [ 60  82   5  34  35   7   1   1  62  22]
  [ 93  30  40  50  85  18  29  82  53  66]
  [ 38  52  55  27  17  61  68  57  34  33]
  [ 97  55  22  43  39  40  98  50  61  11]
  [ 56  27  16  18   2  72  15  74  95  81]
  [ 71  21  99  83  57  83  51  68  96  84]
  [ 19  63  37  24  56  66   5  32  74  15]
  [ 20  22  38  53  88  13  42  75  51  91]]

 [[ 48  27  82  55  93  35  79   9  93   2]
  [ 24  22  19  80  91  69  93  28  48  34]
  [  8  66  44  87  30  87   1  74  17  67]
  [ 36  93  47  71   8  57  94   5  42  75]
  [ 98  29  80  66  63  86  34  77  76  60]
  [ 57  84  32  94  86  90  55  43  89  16]
  [ 90  82  62  68  73  57  44   1  56  51]
  [ 49   3  56  31  71  94  92  99  72  17]
  [ 28  68  31  46  66  97  81  25  41  65]
  [ 59   9  99  59  43  82   3  42  52  90]]]


In [152]:
z= np.where(x < 50, 2, 1)
print(z)

[[[1 1 2 2 1 1 2 2 1 1]
  [2 2 1 1 2 1 2 2 2 2]
  [2 2 2 1 1 1 2 2 1 2]
  [2 1 2 2 2 2 2 1 1 1]
  [2 1 1 1 1 2 2 1 2 2]
  [2 1 2 1 2 1 2 2 2 2]
  [2 2 2 1 2 2 2 2 2 1]
  [2 1 1 1 1 2 2 2 1 2]
  [2 2 1 2 1 2 2 1 1 2]
  [2 1 1 1 2 2 1 2 2 1]]

 [[2 1 2 1 2 2 2 2 1 2]
  [1 2 2 1 2 1 1 2 1 1]
  [2 2 2 2 1 2 1 1 2 1]
  [2 2 1 2 1 2 1 2 2 1]
  [1 1 2 2 1 1 2 1 1 1]
  [1 1 2 1 1 2 2 2 1 2]
  [1 1 1 2 1 1 1 1 1 2]
  [2 2 1 2 2 1 1 1 2 2]
  [1 1 2 1 2 2 1 2 2 1]
  [1 1 1 1 1 1 1 1 2 2]]]


In [166]:
print(z[1][5:,5:])

[[2 2 2 1 2]
 [1 1 1 1 2]
 [1 1 1 2 2]
 [2 1 2 2 1]
 [1 1 1 2 2]]


In [160]:
x=np.arange(20,2).reshape(4,5)
x

ValueError: cannot reshape array of size 0 into shape (4,5)