리스트 만드는 속도! 측정

In [1]:
%%time
import time

size = 10000000

# list
x = list(range(size))
y = list(range(size))

start_time = time.time()
z = [x[i]+x[i] for i in range(size)]
print("리스트 걸린 시간 : ", time.time() - start_time)

#numpy
import numpy as np
x = np.arange(size)
y = np.arange(size)

start_time = time.time()
z = x + y
print("Numpy 걸린 시간 : ", time.time()-start_time)

리스트 걸린 시간 :  1.169252634048462
Numpy 걸린 시간 :  0.11060309410095215
Wall time: 2.42 s


ndarray 실습 (리스트 만들기)

In [15]:
a=[1, 2, 3, 4, 5]
x=np.array(a, dtype=np.float32)

In [16]:
type(x)

numpy.ndarray

In [17]:
x.dtype

dtype('float32')

In [26]:
x=np.uint(32)
print(x.dtype)

uint32


In [27]:
x

32

In [29]:
x=np.int(-32)
x

-32

In [32]:
x=np.array([1, 2, 3, 4])
print(x.dtype)

int32


In [33]:
x = np.float32([1, 2, 3, 4])
print(x.dtype)
x

float32


array([1., 2., 3., 4.], dtype=float32)

In [34]:
x = np.int32(x)
print(x)
np.issubdtype(x.dtype, np.int32)

[1 2 3 4]


True

다차원 ndarray

In [35]:
x=np.array(1)
print(x.shape)
print(x.ndim)
print(x.size)

()
0
1


In [36]:
x=np.array([1,2,3])
print(x.shape)
print(x.ndim)
print(x.size)

(3,)
1
3


In [38]:
x=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(x.shape)
print(x.ndim)
print(x.size)

(2, 3, 3)
3
18


arange 실습

In [41]:
x=np.arange(10)
print(x)
x

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
x=np.arange(10.0)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [44]:
x=np.arange(1, 10, 2)
print(x)

[1 3 5 7 9]


In [45]:
x=np.arange(1, 10, 0.5)
print(x)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [46]:
x=np.arange(10, 1, -0.5)
print(x)

[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5  2.   1.5]


In [48]:
x=np.linspace(1, 20, 5)
x

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [49]:
x=np.linspace(1, 20, 10, endpoint=False)
x

array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1])

In [51]:
x=np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [53]:
x=np.arange(24).reshape(2,3,4)
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [54]:
x=np.arange(16).reshape(2,2,2,2)
print(x)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [55]:
x=np.array([[1,2],[3,4],[5,6]])
print(x)
print(x.reshape(2,3))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [56]:
x=np.arange(9).reshape(3,-1)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
