In [3]:
import pandas as pd
import numpy as np

# Series

In [5]:
x=[1, 2, 3, 4, 5]
s=pd.Series(x)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [6]:
x=np.array([1, 2, 3, 4, 5])
s=pd.Series(x)
s

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [7]:
x[0]

1

In [10]:
x[1:3]

array([2, 3])

In [11]:
x[::-1]

array([5, 4, 3, 2, 1])

In [12]:
x[x>3]

array([4, 5])

In [13]:
x

array([1, 2, 3, 4, 5])

In [14]:
x+1

array([2, 3, 4, 5, 6])

In [15]:
x*10

array([10, 20, 30, 40, 50])

In [16]:
x+x

array([ 2,  4,  6,  8, 10])

In [9]:
s2 = pd.Series(x, index=['a', 'b', 'c', 'd', 'e'])
s2

a    1
b    2
c    3
d    4
e    5
dtype: int32

In [17]:
s2[1:3]

b    2
c    3
dtype: int32

In [20]:
s2['b':'d'] #문자로 하면 범위가 모두 포함된다.

b    2
c    3
d    4
dtype: int32

# series index

In [21]:
print(s.index)

RangeIndex(start=0, stop=5, step=1)


In [22]:
print(list(s.index))

[0, 1, 2, 3, 4]


In [23]:
print(s.values)

[1 2 3 4 5]


In [25]:
print(type(list(s.values)))

<class 'list'>


In [46]:
x=[1, 2, 3, 4, 5]
s2=pd.Series(x, index=['a', 'b', 'c', 'd', 'e'])
print(s2['a':'b'])

a    1
b    2
dtype: int64


* 딕셔너리 to Series

In [30]:
x={"수학":90, "영어": 80, "과학":95, "미술":80}
x=pd.Series(x)
x

수학    90
영어    80
과학    95
미술    80
dtype: int64

In [31]:
x['수학']

90

In [33]:
x["영어":]

영어    80
과학    95
미술    80
dtype: int64

In [34]:
x2=pd.Series(x, index=["수학", "영어", "과학"])
x2

수학    90
영어    80
과학    95
dtype: int64

* Multi Index

In [44]:
student1 = {"수학":90, "영어":80, "과학": 95, "미술":80}
student2 = {"수학":70, "영어":90, "과학": 100, "미술":70}

# index_1 = ['홍길동', '홍길동','홍길동','홍길동','홍길동', '이몽룡', '이몽룡', '이몽룡', '이몽룡', '이몽룡']
index_1 = ['홍길동' for i in range(4)]+['이몽룡' for i in range(4)]
print("index_1 \n", index_1)

# index_2= = ['수학','영어', '과학', '미술', ...]
index_2 = [sub for sub in student1]+[sub for sub in student2]
print("index_2 \n", index_2)

values = list(student1.values()) + list(student2.values())
print(values)

students = pd.Series(values, index=[index_1, index_2])
print(students)

index_1 
 ['홍길동', '홍길동', '홍길동', '홍길동', '이몽룡', '이몽룡', '이몽룡', '이몽룡']
index_2 
 ['수학', '영어', '과학', '미술', '수학', '영어', '과학', '미술']
[90, 80, 95, 80, 70, 90, 100, 70]
홍길동  수학     90
     영어     80
     과학     95
     미술     80
이몽룡  수학     70
     영어     90
     과학    100
     미술     70
dtype: int64


In [39]:
students['홍길동']['영어']

80

# 결측값 처리방법 (NaN None)

In [64]:
x=[1, None, 2, None, 3, 4, None]
x = pd.Series(x)
x

0    1.0
1    NaN
2    2.0
3    NaN
4    3.0
5    4.0
6    NaN
dtype: float64

In [50]:
print(x.sum())
print(x.max())
print(x.min())

10.0
4.0
1.0


In [59]:
print(x.isnull().sum())
print(x.notnull().sum())

3
4


In [62]:
x.dropna()


0    1.0
2    2.0
4    3.0
5    4.0
dtype: float64

In [65]:
x.fillna(0)

0    1.0
1    0.0
2    2.0
3    0.0
4    3.0
5    4.0
6    0.0
dtype: float64

In [63]:
x

0    1.0
1    NaN
2    2.0
3    NaN
4    3.0
5    4.0
6    NaN
dtype: float64

# concat

In [68]:
x=pd.Series([1, 2, 3])
y=pd.Series([4, 5, 6])
z=pd.Series([7, 8, 9])
print(x)
print(y)
print(z)

pd.concat([x, y, z])

0    1
1    2
2    3
dtype: int64
0    4
1    5
2    6
dtype: int64
0    7
1    8
2    9
dtype: int64


0    1
1    2
2    3
0    4
1    5
2    6
0    7
1    8
2    9
dtype: int64

In [69]:
pd.concat([x, y, z], verify_integrity=True)

ValueError: Indexes have overlapping values: Int64Index([0, 1, 2], dtype='int64')

In [71]:
pd.concat([x, y, z], ignore_index=True)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [72]:
pd.concat([x, y, z], ignore_index=True, axis=1)

0  1  2
0  1  4  7
1  2  5  8
2  3  6  9

In [75]:
x=pd.Series([1, 2, 3, 4])
y = pd.Series([5, 6, 7])
z=pd.Series([8, 9, 10])

print(x)
print(y)
print(z)

pd.concat([x, y, z])
pd.concat([x, y, z], axis=1)

0    1
1    2
2    3
3    4
dtype: int64
0    5
1    6
2    7
dtype: int64
0     8
1     9
2    10
dtype: int64


0    1     2
0  1  5.0   8.0
1  2  6.0   9.0
2  3  7.0  10.0
3  4  NaN   NaN

In [82]:
pd.concat([x, y, z], axis=1, join='inner')

0  1   2
0  1  5   8
1  2  6   9
2  3  7  10

In [83]:
pd.concat([x, y, z], axis=1, join='outer')

0    1     2
0  1  5.0   8.0
1  2  6.0   9.0
2  3  7.0  10.0
3  4  NaN   NaN

# 연산과 집계함수

In [84]:
x = pd.Series([1, 2, 3, 4, 5])
y = pd.Series([6, 7, 8, 9, 0])

In [86]:
print(x.add(10))
print(x.add(y))

0    11
1    12
2    13
3    14
4    15
dtype: int64
0     7
1     9
2    11
3    13
4     5
dtype: int64


In [89]:
print(x.floordiv(2))
print(x.div(2))
print(x.mod(2))

0    0
1    1
2    1
3    2
4    2
dtype: int64
0    0.5
1    1.0
2    1.5
3    2.0
4    2.5
dtype: float64
0    1
1    0
2    1
3    0
4    1
dtype: int64


In [104]:
print(x.mean())

3.0


In [107]:
print(x.head(7))

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [145]:
x = [np.nan, 1, 2, 3, 4, 5]
y = pd.Series([x[np.random.randint(0,6)]for i in range(20)])
print(y)

0     4.0
1     3.0
2     3.0
3     1.0
4     5.0
5     3.0
6     5.0
7     4.0
8     3.0
9     3.0
10    2.0
11    1.0
12    NaN
13    4.0
14    5.0
15    3.0
16    3.0
17    3.0
18    4.0
19    4.0
dtype: float64


In [156]:
print("결측값", y.isnull().sum())

결측값 1


In [149]:
z=y.dropna()
print(z)

0     4.0
1     3.0
2     3.0
3     1.0
4     5.0
5     3.0
6     5.0
7     4.0
8     3.0
9     3.0
10    2.0
11    1.0
13    4.0
14    5.0
15    3.0
16    3.0
17    3.0
18    4.0
19    4.0
dtype: float64


In [157]:
a = z.sum()
b = a/len(z)
print(b)
print(z.mean())


3.3157894736842106
3.3157894736842106


# Data Frame

In [162]:
sales_data = {
 '연도':[2015, 2016, 2017, 2018, 2019, 2020],
 '판매량':[103, 70, 130, 160, 190, 230],
 '매출':[500000, 300000, 400000, 550000, 700000, 680000],
 '순이익':[370000, 190000, 300000, 480000, 600000, 590000]}

In [163]:
df = pd.DataFrame(sales_data)
df

연도  판매량      매출     순이익
0  2015  103  500000  370000
1  2016   70  300000  190000
2  2017  130  400000  300000
3  2018  160  550000  480000
4  2019  190  700000  600000
5  2020  230  680000  590000

In [164]:
df.head(2)

연도  판매량      매출     순이익
0  2015  103  500000  370000
1  2016   70  300000  190000

In [165]:
df.describe()

연도         판매량             매출            순이익
count     6.000000    6.000000       6.000000       6.000000
mean   2017.500000  147.166667  521666.666667  421666.666667
std       1.870829   58.413754  156258.333111  164123.936909
min    2015.000000   70.000000  300000.000000  190000.000000
25%    2016.250000  109.750000  425000.000000  317500.000000
50%    2017.500000  145.000000  525000.000000  425000.000000
75%    2018.750000  182.500000  647500.000000  562500.000000
max    2020.000000  230.000000  700000.000000  600000.000000

In [166]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   연도      6 non-null      int64
 1   판매량     6 non-null      int64
 2   매출      6 non-null      int64
 3   순이익     6 non-null      int64
dtypes: int64(4)
memory usage: 320.0 bytes


In [167]:
df["판매량"]

0    103
1     70
2    130
3    160
4    190
5    230
Name: 판매량, dtype: int64

In [169]:
df.iloc[1:3]

연도  판매량      매출     순이익
1  2016   70  300000  190000
2  2017  130  400000  300000

In [172]:
pd.DataFrame(sales_data, columns=['판매량','매출'], index=df["연도"])

판매량      매출
연도               
2015  103  500000
2016   70  300000
2017  130  400000
2018  160  550000
2019  190  700000
2020  230  680000

In [174]:
%%writefile sales_data.csv
연도,판매량,매출,순익
2015,103,500000,370000
2016,70,300000,190000
2017,130,400000,300000
2018,60,550000,480000
2019,190,700000,600000
2020,230,680000,590000

Writing sales_data.csv


In [189]:
sales_data = pd.read_csv('sales_data.csv', index_col="연도", header=0, sep=',')
sales_data

판매량      매출      순익
연도                       
2015  103  500000  370000
2016   70  300000  190000
2017  130  400000  300000
2018   60  550000  480000
2019  190  700000  600000
2020  230  680000  590000

In [190]:
sales_data.to_csv('sales_data_save.csv', encoding='utf-8')